---
name: Terraform Apply

'on':
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Lambda packages
        run: ./scripts/build_lambdas.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::741139166799:role/service-accounts/aws-sudoblark-management-github-cicd-role
          aws-region: eu-west-2

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          auto_approve: true
          path: ./infrastructure/aws-sudoblark-development
